### PR TITLE
Update Submariner version to 0.12.0-rc1

### PR DESCRIPTION
**Pull request by sridhargaddam**
Signed-off-by: Sridhar Gaddam <sgaddam@redhat.com>

### CODE REVIEW

**Comment by sridhargaddam** [comment]
This needs to be backported to release-2.5 branch

**Review by Jaanki — APPROVED** [review]

**Comment by skitt** [comment]
/hold

I want to see whether dependabot notices rc1.

For patches which need to be backported, you can use the appropriate command to queue a cherry-pick on merge (`/cherrypick release-2.5`).

**Comment by skitt** [comment]
Sorry, of course dependabot doesn’t know about `deploy.sh` :blush: 

/unhold
/approve

**Comment by sridhargaddam** [comment]
Manually cherry-picked via the following PR - https://github.com/stolostron/submariner-addon/pull/323

**Pull request merged**
