### PR TITLE
Trigger a rebuild

### PR DESCRIPTION
**Pull request by dfarrell07**
These two commits undo each other, but hopefully the will trigger a rebuild.

We tried an empty commit in #399 but that didn't work.

### CODE REVIEW

**Comment by dfarrell07** [comment]
>    	github.com/stolostron/submariner-addon/pkg/version	[no test files]

Weird.

**Comment by dfarrell07** [comment]
And now it's passing

**Comment by skitt** [comment]
Ah, an empty PR can’t be approved.

**Pull request merged**
