### PR TITLE
Bump to the latest Submariner operator

### PR DESCRIPTION
**Pull request by skitt**
This requires upgrading the controller runtime for compatibility with
the Prometheus client.

Signed-off-by: Stephen Kitt <skitt@redhat.com>

### CODE REVIEW

**Review by sridhargaddam — APPROVED** [review]
Thanks @skitt

**Review by Jaanki — APPROVED** [review]

**Comment by skitt** [comment]
/test integration

It’s failing with “panic: mkdir /.cache: permission denied”.

**Pull request merged**
