### PR TITLE
Create a ClusterRole to allow brokers.submariner.io object

### PR DESCRIPTION
**Pull request by sridhargaddam**
Starting with ACM 2.5, a user who is installing Submariner
Addon on the ManagedCluster should have permissions to
create/update/read brokers.submariner.io object in the
ManagedClusterSet broker namespace.
This object needs to be created whether Globalnet is
enabled or not.

A clusterAdmin has necessary privileges to create this
object, but for a non-ClusterAdmin, an explicit role has
to be assigned. This PR creates a ClusterRole as part of
Submariner addon initialization. Assigning this ClusterRole
to the respective user has to be done manually.

Fixes: https://github.com/stolostron/submariner-addon/issues/321
Signed-off-by: Sridhar Gaddam <sgaddam@redhat.com>

### CODE REVIEW

**Comment by skitt** [comment]
/approve

For context (for other reviewers), we can’t provide this separate role in the CSV, so we end up granting the addon permissions to take care of it itself.

**Review by Jaanki — APPROVED** [review]

**Comment by Jaanki** [comment]
Is this documented anywhere?

**Comment by sridhargaddam** [comment]
> Is this documented anywhere?

Yes, we have an issue to track it - https://github.com/stolostron/backlog/issues/20552 (Item number 5, point number 2). The Docs team is going to work on the necessary documentation AFAICT. CC @dfarrell07

**Pull request merged**
