### PR TITLE
Enable golangci-lint nilerr linter, fix errors

### PR DESCRIPTION
**Pull request by tpantelis**

### CODE REVIEW

**Comment by dfarrell07** [comment]
I think my golangci-lint update PR will get this new linter working: https://github.com/openshift/release/pull/23023

**Comment by tpantelis** [comment]
> I think my golangci-lint update PR will get this new linter working: [openshift/release#23023](https://github.com/openshift/release/pull/23023)

👍 Thanks - I was going to ask you about that 😄 I thought maybe the latest updates to 2.5 etc had updated the golangci-lint version.

**Comment by dfarrell07** [comment]
> Container test exited with code 2, reason OOMKilled

:thinking:

**Comment by tpantelis** [comment]
> > Container test exited with code 2, reason OOMKilled
> 
> 🤔

Cryptic. 

```
golangci-lint run --timeout 10m
make: *** [Makefile:123: golangci-lint] Killed
{"component":"entrypoint","error":"wrapped process failed: exit status 2","file":"prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2022-01-24T21:07:03Z"} 
[36mINFO[0m[2022-01-24T21:07:10Z] Ran for 6m31s                                
[31mERRO[0m[2022-01-24T21:07:10Z] Some steps failed:                           
[31mERRO[0m[2022-01-24T21:07:10Z] 
  * could not run steps: step golangci-lint failed: test "golangci-lint" failed: the pod ci-op-r6jy3sni/golangci-lint failed after 6m25s (failed containers: test): ContainerFailed one or more containers exited
```

It seems like prow or something timed it out and killed it. Sigh. ☹️

**Comment by tpantelis** [comment]
The [job](https://storage.googleapis.com/origin-ci-test/pr-logs/pull/stolostron_submariner-addon/259/pull-ci-stolostron-submariner-addon-main-golangci-lint/1485729207173517312/build-log.txt) for another PR succeeded and took 1m 31s. I don't see how just adding the `nilerr` linter could cause it to take 6m 31s.

**Comment by skitt** [comment]
> > Container test exited with code 2, reason OOMKilled
> 
> thinking

That means it ran out of memory, perhaps we need to increase the allocated RAM in the job configuration.

**Comment by dfarrell07** [comment]
> Container test exited with code 2, reason OOMKilled

 Here's a PR to increase the RAM limits by 50%: https://github.com/openshift/release/pull/25609

**Comment by dfarrell07** [comment]
And it's working now :partying_face:

**Pull request merged**
