### PR TITLE
Add RHOS Support

### PR DESCRIPTION
**Pull request by vthapar**
Signed-off-by: Vishal Thapar <5137689+vthapar@users.noreply.github.com>

### CODE REVIEW

**Comment by vthapar** [comment]
Cherry pick from https://github.com/stolostron/submariner-addon/pull/298

**Comment by sridhargaddam** [comment]
@vthapar The number of lines that got changed seems to be different from the original PR. Is this a clean cherry-pick or did you have to manually fix some merge conflicts?

**Comment by skitt** [comment]
Please re-do this with `-x` (`git cherry-pick -x`) so that the original commit references are preserved, and please also actually squash the commits.

**Comment by vthapar** [comment]
> Please re-do this with `-x` (`git cherry-pick -x`) so that the original commit references are preserved, and please also actually squash the commits.

@skitt Done

**Pull request merged**
