### PR TITLE
Rebuild images for CVE updates

### PR DESCRIPTION
**Pull request by skitt**
Signed-off-by: Stephen Kitt <skitt@redhat.com>

### CODE REVIEW

**Comment by skitt** [comment]
@tpantelis why did you close this?

**Comment by tpantelis** [comment]
> @tpantelis why did you close this?

There were 3 other similar "noop" PRs - I merged one of them.

**Comment by tpantelis** [comment]
> > @tpantelis why did you close this?
> 
> There were 3 other similar "noop" PRs - I merged one of them.

oops - I didn't notice this was on a different branch.

**Pull request merged**
