### PR TITLE
Revert "Create ClusterRole to allow brokers.submariner.io object"

### PR DESCRIPTION
**Pull request by skitt**
This reverts commit a0ccd17fbb42b59bc68da4618cf4e1937e5a8bf0.

Introducing a separate ClusterRole in this fashion breaks the catalog:

    Error: ClusterRole must be defined via permissions in CSV, not in
    bundle file
    access-to-brokers-submariner-crd_rbac.authorization.k8s.io_v1_clusterrole.yaml

See for example
<https://github.com/stolostron/release/actions/runs/1890724453>.

Signed-off-by: Stephen Kitt <skitt@redhat.com>

### CODE REVIEW

**Comment by sridhargaddam** [comment]
> ClusterRole must be defined via permissions in CSV

Is this the right way to add any new CR? - https://github.com/stolostron/submariner-addon/pull/291/files

**Review by sridhargaddam — APPROVED** [review]

**Comment by skitt** [comment]
/hold

This needs the manifest updates as well.

**Pull request merged**
