### PR TITLE
Bump ManagedClusterSet version to v1beta2

### PR DESCRIPTION
**Pull request by tpantelis**
Fixes https://github.com/stolostron/backlog/issues/25784

Signed-off-by: Tom Pantelis <tompantelis@gmail.com>

### CODE REVIEW

**Review by Jaanki — APPROVED** [review]

**Comment by tpantelis** [comment]
The `sonarcloud` job fails due to code coverage - we can ignore it.

**Comment by tpantelis** [comment]
@skitt This needs to be manually merged.

**Pull request merged**
