### PR TITLE
Fix missing secrets in SA for brokerInfo

### LINKED ISSUE #463: Submariner fails to deploy on OCP 4.11.0+
SubmarinerAddon Agent on hub cluster fails to create brokerInfo object with following error:

```
E0728 07:49:16.661477       1 base_controller.go:270] "SubmarinerAgentController" controller failed to sync "red/submariner", err: failed to create submariner brokerInfo of cluster red : ServiceAccount subm-broker/red does not have a secret of type token
```
Without brokerInfo object, submariner doesn't get deployed. This is issue with OCP 4.11.0+ because of change in how K8s 1.24+ creates Secrets for SAs.

### PR DESCRIPTION
**Pull request by vthapar**
Fixes #463

Signed-off-by: Vishal Thapar <5137689+vthapar@users.noreply.github.com>

### CODE REVIEW

**Review by tpantelis — APPROVED** [review]

**Comment by nyechiel** [comment]
@vthapar @skitt it looks like this was automatically synced into `release-2.6`, but should we also cherry pick to `release-2.5`?

**Comment by vthapar** [comment]
Don't think so as this is mainly needed for 4.11 and 2.5 only supports up to 4.10.

**Comment by nyechiel** [comment]
> Don't think so as this is mainly needed for 4.11 and 2.5 only supports up to 4.10.

2.5 should support 4.11 in a future 2.5.z.

**Pull request merged**
