### PR TITLE
Reduce sharedInformer memory usage

### PR DESCRIPTION
**Pull request by vthapar**
Trim ManagedFields to reduce shared informer memory usage. This requires informers generated with  newer version of k8s/client-go [0.29] so currently it is done for following informers:
     - k8s
     - submarinerconfig

Rest informers should be updated once WithTransform() is available.

Refer: https://github.com/kubernetes/kubernetes/pull/118455

DependsOn #1318

### CODE REVIEW

**Comment by skitt** [comment]
https://github.com/open-cluster-management-io/api/pull/320 updates the OCM informers.

**Comment by tpantelis** [comment]
> [open-cluster-management-io/api#320](https://github.com/open-cluster-management-io/api/pull/320) updates the OCM informers.

Cool. I updated the code to use it. The work API needs to be updated as well but we can do that later. This PR gets most of them.

**Comment by vthapar** [comment]
@tpantelis We need to override the sonarcheck for this.

**Pull request merged**
