### PR TITLE
Upgrade Go to 1.17

### PR DESCRIPTION
**Pull request by tpantelis**
As per https://github.com/open-cluster-management/backlog/issues/15570.

### CODE REVIEW

**Comment by skitt** [comment]
/hold

pending clarification on go-toolset

**Comment by tpantelis** [comment]
verify-deps is failing:

```
cd "/tmp/tmp.vv8WIhoY7A"/updated && go mod tidy && go mod vendor && go mod verify
go mod tidy: go.mod file indicates go 1.17, but maximum supported version is 1.16
```

Apparently, for whatever reason, this job is using go 1.16.

**Comment by tpantelis** [comment]
> verify-deps is failing:
> 
> ```
> cd "/tmp/tmp.vv8WIhoY7A"/updated && go mod tidy && go mod vendor && go mod verify
> go mod tidy: go.mod file indicates go 1.17, but maximum supported version is 1.16
> ```
> 
> Apparently, for whatever reason, this job is using go 1.16.

@dfarrell07 @skitt  Hmm...  so following similar PRs in other projects I updated to 1.17 in the _Dockerfile_:

`FROM registry.ci.openshift.org/open-cluster-management/builder:go1.17-linux AS builder`

I assumed all the prow jobs used this  _Dockerfile_  but apparently `verify-deps` doesn't? I changed it back to **go1.16** - same results - all jobs succeeded except `verify-deps`. Hard to know what's actually using the _Dockerfile_ and unclear how to get `verify-deps` to use 1.17.

**Pull request closed without merging**
