### PR TITLE
Cloud-prepare - add support for ROSA

### PR DESCRIPTION
**Pull request by yboaron**
Don't run cloud-prepare for ROSA

Fixes: https://github.com/stolostron/submariner-addon/issues/509

Signed-off-by: Yossi Boaron <yboaron@redhat.com>

### CODE REVIEW

**Comment by yboaron** [comment]
cc @tpantelis @sridhargaddam

**Comment by yboaron** [comment]
cc @aswinsuryan @dfarrell07

**Review by aswinsuryan — APPROVED** [review]

**Pull request merged**
