### PR TITLE
Move AWS cloud preparation to the spoke

### PR DESCRIPTION
**Pull request by tpantelis**
See individual commits for details.

Fixes https://github.com/stolostron/submariner-addon/issues/218.

### CODE REVIEW

**Comment by tpantelis** [comment]
/hold
This is targeted for 2.8.

**Review by aswinsuryan — APPROVED** [review]
Tested in ACM, preparation happens without any error.

**Comment by tpantelis** [comment]
/cc @aswinsuryan @skitt 

This is all set. I bumped cloud-prepare to get the duplicate SG check.

**Comment by skitt** [comment]
/approve

Once this gets a second vote, let me know and I’ll force-merge it.

**Pull request merged**
