### PR TITLE
Bump to K8s version 25.0

### PR DESCRIPTION
**Pull request by tpantelis**
Signed-off-by: Tom Pantelis <tompantelis@gmail.com>

### CODE REVIEW

**Comment by skitt** [comment]
/hold

This now passes with the updated `golangci-lint`, @tpantelis can you clean the PR up? The first two commits should be squashed, and presumably the last one dropped.

**Comment by tpantelis** [comment]
> This now passes with the updated `golangci-lint`, @tpantelis can you clean the PR up? The first two commits should be squashed, and presumably the last one dropped.

Done.

**Pull request merged**
