### PR TITLE
Update Dockerfile references for Konflux

### PR DESCRIPTION
**Pull request by dfarrell07**
Relates-to: https://issues.redhat.com/browse/ACM-10822

### CODE REVIEW

**Comment by skitt** [comment]
I suspect this won’t make any difference until the Konflux setup is copied from the 2.10 branch...

**Comment by dfarrell07** [comment]
> I suspect this won’t make any difference until the Konflux setup is copied from the 2.10 branch...

I should send it to 2.10 first in this case, it seems.

**Comment by dfarrell07** [comment]
> > I suspect this won’t make any difference until the Konflux setup is copied from the 2.10 branch...
> 
> I should send it to 2.10 first in this case, it seems.

https://github.com/stolostron/submariner-addon/pull/1404

**Pull request closed without merging**
