### PR TITLE
Bump addon framework to 0.7.1

### PR DESCRIPTION
**Pull request by zhujian7**
Bump addon framework to 0.7.1 to fix the similar [issue](https://github.com/stolostron/multicloud-operators-foundation/pull/644)

### CODE REVIEW

**Comment by zhujian7** [comment]
cc @skitt @qiujian16

**Comment by skitt** [comment]
@zhujian7 if I understand the issue correctly, we fixed this with #1018 — does this miss something that the addon framework fixes?

**Comment by zhujian7** [comment]
Hi @skitt it is a new bug fixed in addon-framework 0.7.1 yesterday.

**Comment by skitt** [comment]
Thanks for the info @zhujian7!

/lgtm

**Pull request merged**
